# Generated by Django 4.1.3 on 2023-03-26 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog_category_blog_created_date_blog_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(blank=True, help_text='Tell us what you are thinking in maximum 250 words.', max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 26)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modified_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 26)),
        ),
    ]
