# Generated by Django 4.1.3 on 2023-04-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_userprofile_followers_userprofile_follows'),
        ('Blog', '0006_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='User.userprofile'),
        ),
    ]
