# Generated by Django 4.1.3 on 2023-03-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_userprofile_code_userprofile_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
