# Generated by Django 4.1.3 on 2023-04-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_userprofile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, default=1, null=True, related_name='followed_by', to='User.userprofile'),
        ),
    ]
