# Generated by Django 4.1.3 on 2023-04-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_userprofile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
    ]
